<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!--app config-->
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!--trimming and optimizing config-->
		<PublishAot>true</PublishAot>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishTrimmed>true</PublishTrimmed>
		<InvariantGlobalization>true</InvariantGlobalization>

		<!--single file config-->
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.54.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\core\core.csproj" />
	</ItemGroup>

</Project>